name: coverage
on:
  push:
    branches: ['*']
jobs:
  tests:
    strategy:
      matrix:
        python: [3.11]
    runs-on: ubuntu-latest

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        run: |
          pip install requests
          pip install -r requirements.txt
          pip install pytest coverage codecov
      - name: Run tests with coverage
        run: |
          coverage run -m pytest --doctest-modules
          coverage report -m
          COVERAGE_PERCENT=$(coverage report | tail -1 | awk '{print $NF}' | sed 's/%//')
          echo "Coverage: $COVERAGE_PERCENT%"
          if [ $COVERAGE_PERCENT -ge 90 ]; then
            echo "status=passed" >> $GITHUB_ENV
          else
            echo "status=failed" >> $GITHUB_ENV
          fi

      - name: Create coverage badge
        run: |
          if [ "$status" = "passed" ]; then
            COLOR="brightgreen"
          else
            COLOR="red"
          fi
          echo "https://img.shields.io/badge/coverage-$status-$COLOR" > badge_url.txt
        shell: bash
